version: '3.4'

name: TalkNest
services:
  TalkNest:
    image: talknest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT=Docker"
      - ASPNETCORE_URLS=http://+:8000
    ports: ["8000:8000"]
    depends_on:
        postgres:
            condition: service_healthy


  postgres:
    image: "postgres:14"
    restart: always
    ports: [ "5030:5432" ]
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    command: postgres -c 'log_statement=all' -c 'max_connections=500'

    volumes:
           - "./logs:/var/lib/postgresql/logs:rw"
    deploy:
      resources:
        limits:
          memory: 100M
        reservations:
          memory: 50M
    healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U talknest -d talknestdb'"]
        interval: 10s
        timeout: 3s
        retries: 3

